version: '3.1'

services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
  api1_1:
    build: api1
    depends_on:
        - zookeeper
  api1_2:
    build: api1
    depends_on:
        - zookeeper
  api2_1:
    build: api2
    depends_on:
        - zookeeper
  api2_2:
    build: api2
    depends_on:
        - zookeeper
  api3_1:
    build: api3
    depends_on:
        - zookeeper
  api3_2:
    build: api3
    depends_on:
        - zookeeper
  api4_1:
    build: api4
    depends_on:
        - zookeeper
  api4_2:
    build: api4
    depends_on:
        - zookeeper
  controller:
    build: controller
    ports:
      - 8081:8081
    depends_on:
        - zookeeper
        - api1_1
        - api1_2
        - api2_1
        - api2_2
        - api3_1
        - api3_2
        - api4_1
        - api4_2
